site_name:  "MSTUCA CTF Platform"
site_url:   "https://try-h4rder.github.io/mstucactf-platform/"

repo_url:   "https://github.com/try-h4rder/mstucactf-platform/"
repo_name:  "mstucactf-platform"

nav:
  - Главная:   "index.md"
  - Начало:
    - "Знакомство с ИБ и CTF":  "start/intro_ctf.md"
    - "Знакомство с Linux":     "start/linux.md"
    - "Программирование":       "start/programming.md"
    - "Криптография":           "start/crypto.md"
    - "Сети":                   "start/network.md"
    - "Веб-технологии":         "start/web.md"
    - "Обратная разработка":    "start/reverse.md"
    - "Бинарные уязвимости":    "start/pwn.md"
    - "CTF — Task-based":        "start/task_based.md"
  - Вход:  "login.md"
  - О проекте:  "about.md"

theme:
  name:     "material"
  language: "ru"

  favicon:  "images/font-awesome-brands-solid.svg"
  features:
    - navigation.instant  # SPA
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
  icon:
    logo:   "fontawesome/brands/font-awesome"
    repo:   "fontawesome/brands/github"
  
  palette:
    # Palette toggle for light mode
    - media:  "(prefers-color-scheme: light)"
      scheme: "default"
      toggle:
        icon: "material/weather-night"
        name: "Включить тёмный режим"

    # Palette toggle for dark mode
    - media:  "(prefers-color-scheme: dark)"
      scheme: "slate"
      toggle:
        icon: "material/weather-sunny"
        name: "Включить светлый режим"

plugins:
  - mkdocs_quiz:
      custom_translations:
        ru: translations/ru.po
      auto_number: true

extra:
  social:
    - icon: "fontawesome/brands/telegram"
      link: "https://t.me/+CUAjrjoOB-Y2NDg6"
      name: "t.me"

extra_css:
  - stylesheets/media-switcher.css
  - https://cdn.jsdelivr.net/npm/firebaseui@6.1.0/dist/firebaseui.css
  - stylesheets/firebase-auth.css

extra_javascript:
  - https://www.gstatic.com/firebasejs/12.6.0/firebase-app-compat.js
  - https://www.gstatic.com/firebasejs/12.6.0/firebase-auth-compat.js
  - https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore-compat.js
  - https://cdn.jsdelivr.net/npm/firebaseui@6.1.0/dist/firebaseui.js
  - javascripts/firebase-auth.js
  - javascripts/firebase-send-quiz.js
  - javascripts/firebase-sync-quiz.js
  - javascripts/firebase-draw-scoreboard.js
  - javascripts/spa-observer.js

copyright: Copyright &copy; 2026 Aslan Ashnokov

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true